### ISSUE TITLE
Draw tiles below GUI background.

### ISSUE THREAD

**Issue by micycle1** [b3nson/petter#51]
Tiles are drawn over the right-hand-side GUI background, but not the sliders and buttons (as intended).

Change the draw order such that tiles are drawn below the GUI background.

**Comment by b3nson** [comment]
Haha, yeah, you're right... 😄 
I liked it somehow when it first "happened", so i left it like that ever since.
It accentuates the experimental character of petter. :) 
But thanks for letting me know. 👍
